---
version: "3"
services:
  etcd:
    image: gcr.io/google_containers/etcd-amd64:3.1.11
    command:
      - etcd
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://127.0.0.1:2379
      - --data-dir=/var/lib/etcd
    networks:
      - sandwich
    volumes:
      - etcd:/var/lib/etcd
    logging:  # Don't need to see these logs
      driver: none
  kube-api:
    image: gcr.io/google_containers/hyperkube-amd64:v1.9.2
    command:
      - kube-apiserver
      - --etcd-servers=http://etcd:2379
      - --service-cluster-ip-range=10.96.0.0/16
      - --admission-control=Initializers,NamespaceExists,NamespaceLifecycle
      - --insecure-bind-address=0.0.0.0
      - --anonymous-auth=true
    networks:
      - sandwich
    ports:
      - "8081:8080"
    logging:  # Don't need to see these logs
      driver: none
  # Controller manager is needed to run the namespace lifecycle
  kube-controller-manager:
    image: gcr.io/google_containers/kube-controller-manager-amd64:v1.9.2
    command:
      - kube-controller-manager
      - --controllers=*,tokencleaner  # TODO: figure out what controllers we actually need
      - --address=127.0.0.1
      - --master=http://kube-api:8080
    networks:
      - sandwich
    logging:  # Don't need to see these logs
      driver: none
  # Redis to do cache stuffs
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    logging:  # Don't need to see these logs
      driver: none
    networks:
      - sandwich
  deli-counter:
    image: sandwichcloud/deli-counter:latest
    environment:
      - KUBEMASTER=http://kube-api:8080
      - AUTH_FERNET_KEYS=oT7YhuLp37WTBtfI0I63xwg0iV6vmb-VQwVK7OHfV1U=
      - OPENID_ISSUER_URL=http://localhost:8080
      - OPENID_CLIENT_ID=asdasd
      - OPENID_CLIENT_SECRET=asdasd
      - OPENID_EMAIL_CLAIM=email
      - OPENID_GROUPS_CLAIM=groups
      - REDIS_URL=redis://redis:6379
    networks:
      - sandwich
    ports:
      - "8080:8080"
  deli-manager:
    image: sandwichcloud/deli-manager:latest
    env_file:
      - .env
    environment:
      - KUBEMASTER=http://kube-api:8080
      - REDIS_URL=redis://redis:6379
    networks:
      - sandwich
  deli-menu:
    image: sandwichcloud/deli-menu:latest
    environment:
      - KUBEMASTER=http://kube-api:8080
      - FERNET_KEY=oT7YhuLp37WTBtfI0I63xwg0iV6vmb-VQwVK7OHfV1U=
      - REDIS_URL=redis://redis:6379
    networks:
      - sandwich
    ports:
      - "13370:13370"

networks:
  sandwich:

volumes:
  etcd:
